ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG INSTALL_DEPS_CMD
RUN sh -c "${INSTALL_DEPS_CMD}"
RUN python3 -m pip install tox build

COPY tests/entrypoint.sh /entrypoint.sh

WORKDIR /dnf-shim
COPY . .

WORKDIR /
ENTRYPOINT ["/entrypoint.sh"]
