ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG INSTALL_DEPS_CMD
RUN sh -c "${INSTALL_DEPS_CMD}"

COPY tests/entrypoint.sh /entrypoint.sh

WORKDIR /libdnf-shim
COPY . .

WORKDIR /
ENTRYPOINT ["/entrypoint.sh"]
